version: "3"

services:
  app:
    build:
      context: ./
    container_name: blueengineering_server
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DATABASE_CLIENT: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: bluecore_db
      DATABASE_USERNAME: bgadmin
      DATABASE_PASSWORD: db2695555a336ab47dfb9b33
    volumes:
      - ./:/srv/app
    ports:
      - 0.0.0.0:8080:80
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: blue_db_service
    restart: unless-stopped
    environment:
      POSTGRES_DB: bluecore_db
      POSTGRES_USER: bgadmin
      POSTGRES_PASSWORD: db2695555a336ab47dfb9b33
    volumes:
      - ./data:/var/lib/postgresql/data
